### ISSUE TITLE
Wrong patch is generated with DiffTimeout = 0

### ISSUE THREAD

**Issue by tkf** [sergi/go-diff#28]
I think the patch generated by the following code is wrong:

```go
package main

import (
	"io"
	"os"

	"github.com/sergi/go-diff/diffmatchpatch"
)

const (
	text1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut risus et enim consectetur convallis a non ipsum. Sed nec nibh cursus, interdum libero vel."
	text2 = "Lorem a ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut risus et enim consectetur convallis a non ipsum. Sed nec nibh cursus, interdum liberovel."
)

func main() {
	dmp := diffmatchpatch.New()
	dmp.DiffTimeout = 0
	// dmp.DiffTimeout = time.Hour  // it works
	diffs := dmp.DiffMain(text1, text2, true)
	diffs = dmp.DiffCleanupSemantic(diffs)
	patches := dmp.PatchMake(text1, diffs)
	io.WriteString(os.Stdout, dmp.PatchToText(patches))
}
```

It generates:

```diff
@@ -1,17 +1,18 @@
 Lorem
+a
 ro
-
 um dolor
```

However, the correct patch would be:

```diff
@@ -1,14 +1,16 @@
 Lorem
+a
 ipsum do
@@ -148,13 +148,12 @@
 m libero
-
 vel.
```

which is generated by setting `dmp.DiffTimeout = time.Hour`.  Note that C++ implementation (with timeout=0) also generates the latter patch.

**Comment by jeremejevs** [comment]
Setting `checklines` to `false` produces a correct patch. Don't know what the cause is, but from a quick glance at `diffCompute`, it seems that it makes no sense to have no deadline and `checklines` enabled at the same time, since they have contradictory effects (`DiffTimeout = 0` tells the lib to take its time and produce the best diff possible, while `checklines = true` tells it to compromise quality for performance). This combo is completely missing in the tests.

**Comment by zimmski** [comment]
I tested your example with the latest master, it outputs

```diff
@@ -1,14 +1,16 @@
 Lorem 
+a 
 ipsum do
@@ -148,13 +148,12 @@
 m libero
- 
 vel.
```

**Comment by zimmski** [comment]
To be more verbose. I can confirm that with the old version you were probably using (i.e. bc2ef1260ca6e3888a54bae1bd3260b0aae53e52) the problem was still present, but now with the current master it is not. Please give it a whirl :-)

I can also confirm that the provided example and its patch make sense. I will add is as a test case and I will adapt the current deadline code because it does not make any sense. At the moment, if 0 or a negative deadline is given, the code will use a deadline of a year. I mean, if we do not want a deadline, we are serious about that, right?
